from .StoragePartitionByName					import StoragePartitionByNameRule
from .ArticleNotStartsWithParam 				import ArticleNotStartsWithParamRule
from .ArticleEndsWithParam 						import ArticleEndsWithParamRule
from .ArticleStartsWithParam 					import ArticleStartsWithParamRule
from .ArticleGetFromAnotherColumn 				import ArticleGetFromAnotherColumnRule
from .ArticleAddZeroIfLessThenParamAndNumeric 	import ArticleAddZeroIfLessThenParamAndNumericRule
from .ArticleAddZerosIfLessThenParamAndNumeric 	import ArticleAddZerosIfLessThenParamAndNumericRule
from .RemoveParamFromArticle 					import RemoveParamFromArticleRule
from .ArticleAddParamIfNumeric 					import ArticleAddParamIfNumericRule
from .ArticleIfRusGetFromAnotherColumn 			import ArticleIfRusGetFromAnotherColumnRule
from .ArticleIfLenLessParam1StartsWithParam2 	import ArticleIfLenLessParam1StartsWithParam2Rule
from .ArticleGetFromColumn1SplitByParam2TakePart3 import ArticleGetFromColumn1SplitByParam2TakePart3Rule
from .ArticleRemoveParams 						import ArticleRemoveParamsRule
from .ArticleCutByParam 						import ArticleCutByParamRule
from .BrandSetValue 							import BrandSetValueRule
from .BrandGetFromColumn 						import BrandGetFromColumnRule
from .BrandSetForArticles 						import BrandSetForArticlesRule
from .BrandSetByArticlePrefix 					import BrandSetByArticlePrefixRule
from .BrandSetForParamInArticle 				import BrandSetForParamInArticleRule
from .BrandSetForParamInComment 				import BrandSetForParamInCommentRule
from .PriceMultiplyByParam 						import PriceMultiplyByParamRule
from .PriceMultiplyArticleByParam 				import PriceMultiplyArticleByParamRule
from .QuantitySetZero 							import QuantitySetZeroRule
from .DeleteIfParamInComment 					import DeleteIfParamInCommentRule
from .DeleteIfParamInColumn 					import DeleteIfParamInColumnRule
from .DeleteIfRusInArticle 						import DeleteIfRusInArticleRule
from .DeleteIfParamNotInComment					import DeleteIfParamNotInCommentRule
from .DeleteBrands 								import DeleteBrandsRule
from .RemoveLetterFromEnd 						import RemoveLetterFromEndRule
from .ReplacementColumnOldNew 					import ReplacementColumnOldNewRule
from .SpecialArticleMann 						import SpecialArticleMannRule
from .SpecialArticleAlfaSupplier 				import SpecialArticleAlfaSupplierRule
from .SpecialArticleElitSupKH 					import SpecialArticleElitSupKHRule
from .SpecialPriceIntertoolMultiplier			import SpecialPriceIntertoolMultiplierRule
from .DeleteIfPriceMoreThanParam				import DeleteIfPriceMoreThanParamRule
from .ArticleNotEndsWithParam					import ArticleNotEndsWithParamRule
from .DeleteIfRegExInColumn						import DeleteIfRegExInColumnRule
from .CastrolArticles							import CastrolArticlesRule
from .NgkArticles								import NgkArticlesRule
from .UnicMonroeCommenReplacement				import UnicMonroeCommenReplacementRule
from .DeleteIfValueMoreThanParam				import DeleteIfValueMoreThanParamRule
from .ClearComment								import ClearCommentRule
from .VesnaZerosToCode							import VesnaZerosToCodeRule
from .QuantitySetParam							import QuantitySetParamRule
from .DensoArticles								import DensoArticlesRule
from .PriceMultiplyIfParam1InCol2ByParam3		import PriceMultiplyIfParam1InCol2ByParam3Rule
from .CardonAralPrice							import CardonAralPriceRule
from .DeleteIfValueEqualParam					import DeleteIfValueEqualParamRule
from .SpecialArticleRavenolSupplier				import SpecialArticleRavenolSupplierRule